# Generated by Django 3.1.1 on 2021-06-16 04:36

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_day',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 4, 35, 34, 323790, tzinfo=utc), max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_month',
            field=models.CharField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_day',
            field=models.CharField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_month',
            field=models.CharField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
    ]
